### ISSUE TITLE
Paths in config files are being hardcoded

### ISSUE THREAD

**Issue by hungkien05** [kwz219/NPR4J#6]
## Current state: 
Paths in config files are being hardcoded. For example, here is what one of translate configs for CoCoNut looks like:
 ```
beam: 300
clearml: false
datadir: /home/zhongwenkang2/RawData_Processed/CoCoNut/d4j
modelpath: /home/zhongwenkang2/NPR4J-Models/CoCoNut/CoCoNut_5_save/checkpoint_best.pt
nbest: 300
outputfile: /home/zhongwenkang2/NPR4J_Pred/CoCoNut/CoCoNut_5_b300_d4j.pred
source: buggy
target: fix
taskname: CoCoNut
use_context: true
```

I don't know how to change the paths in the config correctly, which leads to lots of errors in training and translating.

## Enviroment:
- Python 3.8
- OS: Ubuntu 20.04
- Cuda 11.4
- Conda 22.9.0

## Bug reproduce:
Below is one of some bugs I encountered while translating/infering:

```
(npr4j2) MKL_SERVICE_FORCE_INTEL=1 python translate.py -model CoCoNut -config /home/hungnh/Hung/RISE-NPR4J/Config/translate/CoCoNut/CoCoNut_d4j.yaml
Namespace(CoCoNut_lang='buggy', beam=300, clearml=True, cpu=False, data=['/home/hungnh/RawData_Processed/CoCoNut/d4j'], diverse_beam_groups=1, diverse_beam_strength=0.5, fp16=False, fp16_init_scale=128, fp16_scale_window=None, gen_subset='test', left_pad_CoCoNut='True', left_pad_target='False', lenpen=1, log_format=None, log_interval=1000, max_CoCoNut_positions=1024, max_len_a=0, max_len_b=200, max_sentences=1, max_target_positions=1024, max_tokens=None, min_len=1, model_overrides='{}', nbest=300, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, num_shards=1, outputfile='/home/hungnh/prediction/CoCoNut/CoCoNut_attack_d4j.pred', path='/home/hungnh/Thanh/APRExplainer/Data/Pretrained_Models/CoCoNut_Trained/CoCoNut_99_save/checkpoint_best.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None, sampling=False, sampling_temperature=1, sampling_topk=-1, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, target_lang='fix', task='translation', taskname='CoCoNut', unkpen=0, unnormalized=False, upsample_primary=1, use_context=False)
/home/hungnh/RawData_Processed/CoCoNut/d4j/dict.buggy.txt
| [buggy] dictionary: 8 types
| [fix] dictionary: 8 types
| /home/hungnh/RawData_Processed/CoCoNut/d4j test 400 examples
| /home/hungnh/RawData_Processed/CoCoNut/d4j test 400 examples
| ['/home/hungnh/RawData_Processed/CoCoNut/d4j'] test 400 examples
| loading model(s) from /home/hungnh/Pretrained_Models/CoCoNut_Trained/CoCoNut_99_save/checkpoint_best.pt

Traceback (most recent call last):
  File "fairseq/generate.py", line 317, in <module>
    main(args)
  File "fairseq/generate.py", line 55, in main
    models, _ = utils.load_ensemble_for_inference(args.path.split(':'), task, model_arg_overrides=eval(args.model_overrides))
  File "/home/hungnh/NPR4J/fairseq/fairseq/utils.py", line 160, in load_ensemble_for_inference
    model.load_state_dict(state['model'], strict=True)
  File "/home/hungnh/NPR4J/fairseq/fairseq/models/fairseq_model.py", line 64, in load_state_dict
    super().load_state_dict(state_dict, strict)
  File "/home/hungnh/anaconda3/envs/npr4j2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1668, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FConvContextModel:
        size mismatch for encoder.input_encoder.embed_tokens.weight: copying a param with shape torch.Size([97456, 480]) from checkpoint, the shape in current model is torch.Size([8, 480]).
        size mismatch for encoder.context_encoder.embed_tokens.weight: copying a param with shape torch.Size([97456, 480]) from checkpoint, the shape in current model is torch.Size([8, 480]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([43088, 480]) from checkpoint, the shape in current model is torch.Size([8, 480]).
        size mismatch for decoder.fc3.weight: copying a param with shape torch.Size([43088, 480]) from checkpoint, the shape in current model is torch.Size([8, 480]).
        size mismatch for decoder.fc3.bias: copying a param with shape torch.Size([43088]) from checkpoint, the shape in current model is torch.Size([8]).
total_time 3.5991709232330322
```

Here is my config file:
```
beam: 300
clearml: false
datadir: /home/hungnh/RawData_Processed/CoCoNut/d4j
modelpath: /home/hungnh/Pretrained_Models/CoCoNut_Trained/CoCoNut_99_save/checkpoint_best.pt
nbest: 300
outputfile: /home/hungnh/CoCoNut/CoCoNut_d4j.pred
source: buggy
target: fix
taskname: CoCoNut
use_context: true
```

## Expectation:
**Can you please upload general and complete config files for training and translating ?**

Thanks a lot,
Hung

**Comment by kwz219** [comment]
Hi, @hungkien05.
For the bug you reported, I guess it's because you are using wrong dictionaries. "8 types" means there are only 8 words in your dictionary. The function "_Preprocess_CoCoNut_fromRaw_" in _Preprocess_RawData.py_ should be provided with two already generated dictionary files. Are you using the dictionaries uploaded to the google drive along with the models?
By the way, I write a simple instruction to explain the configs at this link:
https://docs.google.com/document/d/1EEheTmFiMcvsgvCtb5BSL4YdlxLiSReweuzqKIshCkE/edit?usp=sharing
I hope this will help you.
If you have any other questions when using NPR4J, please let me know! I'm glad to offer helps.

**Comment by hungkien05** [comment]
Thank you, @kwz219 for your answer and thorough instruction.
Turn out it was my mistake that I didn't include the two dictionary files. It has run well now.
